# Copyright 2006 The Android Open Source Project

ifdef WIFI_DRIVER_MODULE_PATH
LOCAL_CFLAGS += -DWIFI_DRIVER_MODULE_PATH=\"$(WIFI_DRIVER_MODULE_PATH)\"
endif
ifdef WIFI_DRIVER_MODULE_ARG
LOCAL_CFLAGS += -DWIFI_DRIVER_MODULE_ARG=\"$(WIFI_DRIVER_MODULE_ARG)\"
endif
ifdef WIFI_DRIVER_MODULE_NAME
LOCAL_CFLAGS += -DWIFI_DRIVER_MODULE_NAME=\"$(WIFI_DRIVER_MODULE_NAME)\"
endif
ifdef WIFI_FIRMWARE_LOADER
LOCAL_CFLAGS += -DWIFI_FIRMWARE_LOADER=\"$(WIFI_FIRMWARE_LOADER)\"
endif
ifdef WIFI_DRIVER_FW_PATH_STA
LOCAL_CFLAGS += -DWIFI_DRIVER_FW_PATH_STA=\"$(WIFI_DRIVER_FW_PATH_STA)\"
endif
ifdef WIFI_DRIVER_FW_PATH_AP
LOCAL_CFLAGS += -DWIFI_DRIVER_FW_PATH_AP=\"$(WIFI_DRIVER_FW_PATH_AP)\"
endif
ifdef WIFI_DRIVER_FW_PATH_P2P
LOCAL_CFLAGS += -DWIFI_DRIVER_FW_PATH_P2P=\"$(WIFI_DRIVER_FW_PATH_P2P)\"
endif
ifdef WIFI_DRIVER_FW_PATH_PARAM
LOCAL_CFLAGS += -DWIFI_DRIVER_FW_PATH_PARAM=\"$(WIFI_DRIVER_FW_PATH_PARAM)\"
endif

LOCAL_SRC_FILES += wifi/rk_wifi_ctrl.c

ifeq ($(strip $(BOARD_CONNECTIVITY_VENDOR)),Espressif)
LOCAL_CFLAGS +=-DWIFI_ESP8089
endif
ifeq ($(strip $(BOARD_CONNECTIVITY_VENDOR)), MediaTek)
LOCAL_CFLAGS +=-DWIFI_MTK
endif

#add a new branch for android 4.2's way(gwl)
ifeq ($(strip $(FORCE_WIFI_WORK_AS_ANDROID4_2)), true)
LOCAL_SRC_FILES += wifi/wifi_common.c
LOCAL_SRC_FILES += wifi/wifi_old.c
LOCAL_SRC_FILES += wifi/wifi_mt5931.c
else
ifeq ($(strip $(BOARD_CONNECTIVITY_VENDOR)), RealTek)
LOCAL_SRC_FILES += ../realtek/wlan/libhardware_legacy/wifi/wifi_realtek.c
else
ifeq ($(strip $(BOARD_CONNECTIVITY_VENDOR)), MediaTek_mt7601)
LOCAL_SRC_FILES += wifi/wifi_mt7601.c
else
LOCAL_SRC_FILES += wifi/wifi.c
endif
endif
endif

 
ifeq ($(BOARD_WLAN_DEVICE), mtk)
LOCAL_CFLAGS += -DMTK_WIFI_VENDOR
LOCAL_CFLAGS += -DCONFIG_P2P_AUTO_GO_AS_SOFTAP
LOCAL_CFLAGS += -DCONFIG_MT7601_KO_BUILDIN
LOCAL_CFLAGS += -DRAL_USB_WIFI_USED
endif
 

LOCAL_SHARED_LIBRARIES += libnetutils
